#!/bin/bash
IP=$(curl -s ifconfig.me)
echo "============================================"
echo "  ESTADO CONTENEDORES"
echo "============================================"
docker compose ps --format "table {{.Name}}\t{{.Status}}"
echo ""
echo ""
echo "============================================"
echo "  PRACTICA BIGDATA — URLS ACTUALES"
echo "============================================"
echo ""
echo "  Flask (predicción):"
echo "    http://$IP:5001/flights/delays/predict_kafka"
echo ""
echo "  Spark UI:"
echo "    http://$IP:8080"
echo ""
echo "  Grafana:             (admin / admin)"
echo "    http://$IP:3000"
echo ""
echo "  Prometheus:"
echo "    http://$IP:9090"
echo ""
echo "  MinIO consola:       (minioadmin / minioadmin)"
echo "    http://$IP:9001"
echo ""
echo "  MLflow:"
echo "    http://$IP:5002"
echo ""
echo "  Airflow:             (admin / admin)"
echo "    http://$IP:8081"
echo ""

